### ISSUE TITLE
Missing header files

### ISSUE THREAD

**Issue by maximryzhov** [RealityFactory/Genesis3D#1]
Can't build solution, missing include files:
xtra_g3d.h
dplay.h

**Comment by QuestOfDreams** [comment]
xtra_g3d.h should be fixed in the develop branch, see 45ce4aa297e35257e1fa61604ff58129654bc3ee
dplay.h is part of the required DirectX SDK

**Comment by TheRektafire** [comment]
> xtra_g3d.h should be fixed in the develop branch, see [45ce4aa](https://github.com/RealityFactory/Genesis3D/commit/45ce4aa297e35257e1fa61604ff58129654bc3ee) dplay.h is part of the required DirectX SDK

I cloned the `develop` branch (using `git clone --recursive https://github.com/RealityFactory/Genesis3D -b develop`) and still get spammed by errors about `xtra_g3d.h` not being found after upgrading the .vcprojs and trying to build it, how do I actually get rid of these errors? Is there some other version of the source somewhere that actually contains the header that I can get it from?

More specifically these are the errors I get:
```
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D>msbuild Genesis.vcxproj /p:Configuration=Release /p:Platform=x86
MSBuild version 18.10.1-1.26427.6+3cd27c13e for .NET Framework
Build started 9/22/2026 3:52:50 PM.

Project "C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj" on node 1 (default targ
ets).
PrepareForBuild:
  Creating directory ".\Release\".
  Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://ak
  a.ms/cpp/structured-output for more details.
  Creating directory ".\Release\Genesis.tlog\".
InitializeBuildStatus:
  Creating ".\Release\Genesis.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
  Touching ".\Release\Genesis.tlog\unsuccessfulbuild".
ClCompile:
  C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC\14.51.36231\bin\HostX86\x86\CL.exe /c /IC:\progra
  mming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\ /Iinclude /IWorld /IEngine /IEngine\Drivers /IActor /IB
  SP /IMath /IEntities /ISupport /IPhysics /IVFile /IBitmap /IBitmap\Compression /Zi /nologo /W3 /WX- /diagnostics:colu
  mn /Od /Ob2 /Oi /Ot /Oy- /D WIN32 /D NDEBUG /D _LIB /D _CRT_SECURE_NO_WARNINGS /D _VC80_UPGRADE=0x0600 /D _MBCS /Gm-
  /EHsc /MT /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo".\Release/" /Fd"Release/genesis.pdb" /FR".\Release\
  \" /external:W3 /Gd /TC /wd4996 /analyze- /FC /errorReport:queue Actor\Actor.c Actor\Body.c Actor\BodyInst.c Actor\Mo
  tion.c Actor\Path.c Actor\Pose.c Actor\Puppet.c Actor\QKFrame.c Actor\StrBlock.c Actor\TKArray.c Actor\TKEvents.c Act
  or\VKFrame.c Actor\XFArray.c Bitmap\Bitmap.c Bitmap\Bitmap_BlitData.c Bitmap\Bitmap_Gamma.c Bitmap\Compression\PalCre
  ate.c Bitmap\Compression\Palettize.c Bitmap\Compression\PalOptimize.c Bitmap\Compression\Yuv.c Bitmap\PixelFormat.c C
  amera.c CSNetMgr.c Engine\BitmapList.c Engine\Engine.c Engine\FontBmp.c Engine\Logo\A_Corona.c Engine\Logo\A_Streak.c
   Engine\Logo\Corona.c Engine\Logo\Electric.c Engine\Logo\Logo.c Engine\Logo\LogoActor.c Engine\Logo\Streak.c Engine\L
  ogo\WebUrl.c Engine\System.c Entities\Entities.c Font\Font.c Font\wgClip.c Ge.c List.c Math\Box.c Math\CRC32.c Math\E
  xtBox.c Math\Quatern.c Math\Vec3d.c Math\XForm3d.c NetPlay.c Physics\Matrix33.c Physics\PhysicsJoint.c Physics\Physic
  sObject.c Physics\PhysicsSystem.c Sound.c Sound3d.c Sprite.c Support\ErrorLog.c Support\geAssert.c Support\Log.c Supp
  ort\MemPool.c Support\Ram.c Support\RamDLL.c TClip.c Timer.c TSC.c VFile\DirTree.c VFile\DirTreeCommon.c VFile\FSDos.
  c VFile\FSMemory.c VFile\FSVfs.c VFile\VFile.c World\Fog.c World\Frustum.c World\GBSPFile.c World\Light.c World\Plane
  .c World\Surface.c World\Trace.c World\User.c World\Vis.c World\WBitmap.c World\World.c
  Actor.c
  Body.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'Actor/Actor.c')

  discontinue this?
  LOD code goes here:
  BodyInst.c
  Motion.c
  do we want to copy these before returning them?
  finish this
  finish this
  finish this
  Path.c
  Pose.c
  could optimize a name binded setPose by caching the mapping from motionpath[i] to joint[j]
  could optimize this by looping two ways (min(jointcount,pathcount))
  Puppet.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'Actor/Puppet.c')

  QKFrame.c
  StrBlock.c
  TKArray.c
  TKEvents.c
  VKFrame.c
  XFArray.c
  Bitmap.c
  Bitmap_AverageColor : doesn't support palettized yet!
  Bitmap_BlitData.c
  Bitmap_BlitData: inconsistent handling of separates with color keys!
  Bitmap_Blitdata :using assembly DePalettize code
  Bitmap_Gamma.c
  PalCreate.c
  Palettize.c
  PalOptimize.c
  Yuv.c
  Generating Code...
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1479,1): warning C4731:
'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\desktop
\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1496,1): warning C4731:
'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\desktop
\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1554,1): warning C4731:
'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\desktop
\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1616,1): warning C4731:
'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\desktop
\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1633,1): warning C4731:
'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\desktop
\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1654,1): warning C4731:
'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\desktop
\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1730,1): warning C4731:
'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\desktop
\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1755,1): warning C4731:
'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\desktop
\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1798,1): warning C4731:
'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\desktop
\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1814,1): warning C4731:
'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\desktop
\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
  Compiling...
  PixelFormat.c
  Camera.c
  CSNetMgr.c
  BitmapList.c
  Engine.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'Engine/Engine.c')

  FontBmp.c
  A_Corona.c
  A_Streak.c
  Corona.c
  Electric.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'Engine/Logo/Electric.c')

  Logo.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'Engine/Logo/Logo.c')

  LogoActor.c
  Streak.c
  WebUrl.c
  System.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'Engine/System.c')

  Entities.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'Entities/Entities.c')

  Font.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'Font/Font.c')

  wgClip.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'Font/wgClip.c')

  Ge.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'Ge.c')

  List.c
  Generating Code...
  Compiling...
  Box.c
  CRC32.c
  ExtBox.c
  Quatern.c
  Vec3d.c
  XForm3d.c
  NetPlay.c
  Matrix33.c
  PhysicsJoint.c
  PhysicsObject.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'Physics/PhysicsObject.c')

  PhysicsSystem.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Physics\PhysicsSystem.c(242,16): error C2371: 'fm
in': redefinition; different basic types [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis
.vcxproj]
  Sound.c
      C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\ucrt\corecrt_math.h(542,47):
      see declaration of 'fmin'

  Sound3d.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'Sound3d.c')

  Sprite.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'Sprite.c')

  ErrorLog.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Support\ErrorLog.c(185,47): warning C5286: implic
it conversion from enum type 'geErrorLog_ErrorIDEnumType' to enum type 'geErrorLog_ErrorClassType'; use an explicit cas
t to silence this warning [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
  geAssert.c
  Log.c
  MemPool.c
  Ram.c
  RamDLL.c
  Generating Code...
  Compiling...
  TClip.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'TClip.c')

  Timer.c
  timer OFF
  TSC.c
  TSC off
  DirTree.c
  DirTreeCommon.c
  FSDos.c
  FSDos_GetProperties: Time support is not there for directories
  FSMemory.c
  FSVfs.c
  VFile.c
  Casting away const in geVFile_RegisterFileSystem
  Need to propagate returns through VFile_Close
  Fog.c
  Frustum.c
  GBSPFile.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'World/GBSPFile.c')

  Light.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'World/Light.c')

  Plane.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'World/Plane.c')

  Surface.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'World/Surface.c')

  Trace.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'World/Trace.c')

  User.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'World/User.c')

  Vis.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'World/Vis.c')

  WBitmap.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\World\WBitmap.c(608,15): warning C4477: 'sprintf'
 : format string '%x' requires an argument of type 'unsigned int', but variadic argument 1 has type 'geBitmap *' [C:\pr
ogramming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
  World.c
C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inclu
de file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D
\Genesis.vcxproj]
  (compiling source file 'World/World.c')

  Generating Code...
Done Building Project "C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj" (default
targets) -- FAILED.


Build FAILED.

"C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj" (default target) (1) ->
(ClCompile target) ->
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1479,1): warning C4731
: 'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\deskt
op\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1496,1): warning C4731
: 'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\deskt
op\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1554,1): warning C4731
: 'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\deskt
op\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1616,1): warning C4731
: 'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\deskt
op\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1633,1): warning C4731
: 'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\deskt
op\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1654,1): warning C4731
: 'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\deskt
op\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1730,1): warning C4731
: 'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\deskt
op\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1755,1): warning C4731
: 'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\deskt
op\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1798,1): warning C4731
: 'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\deskt
op\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Bitmap\Bitmap_BlitData.c(1814,1): warning C4731
: 'BlitData_DePalettize': frame pointer register 'ebp' modified by inline assembly code [C:\programming\gamedev\c\deskt
op\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Support\ErrorLog.c(185,47): warning C5286: impl
icit conversion from enum type 'geErrorLog_ErrorIDEnumType' to enum type 'geErrorLog_ErrorClassType'; use an explicit c
ast to silence this warning [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\World\WBitmap.c(608,15): warning C4477: 'sprint
f' : format string '%x' requires an argument of type 'unsigned int', but variadic argument 1 has type 'geBitmap *' [C:\
programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj]


"C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.vcxproj" (default target) (1) ->
(ClCompile target) ->
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Physics\PhysicsSystem.c(242,16): error C2371: '
fmin': redefinition; different basic types [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genes
is.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]
  C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis3D\Genesis.h(692,10): error C1083: Cannot open inc
lude file: 'xtra_g3d.h': No such file or directory [C:\programming\gamedev\c\desktop\_thirdparty\_genesis3d\src\Genesis
3D\Genesis.vcxproj]

    12 Warning(s)
    23 Error(s)

Time Elapsed 00:00:11.11
```

**Comment by TheRektafire** [comment]
Oh, simply commenting out the include from `Genesis.h` seemingly fixed all those errors. It also seems like the engine provides its own `fmin` implementation which conflicts with the modern MSVC one which I had to comment out. After searching for it in vscode it seems like it isn't even used anywhere so idk what the point of it being there is.
